name: wflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pip
  - jupyterlab
  - holoviews
  - ca-certificates
  - certifi
  - openssl
  - pip:
      - metaflow
      - dagster
      - dagit